import type { Metadata } from "next";

import "./globals.css";
import {Elms_Sans} from "@/font/font.";
import Header from "@/feature/HOME/header/header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={Elms_Sans.className}
      data-theme="emerald">
      <body className="min-h-full flex flex-col">
      <Header/>
      {children}</body>
    </html>
  );
}
